package constants

const (
	ORDER_STATUS_PENDING   = "PENDING"
	ORDER_STATUS_CONFIRMED = "CONFIRMED"
	ORDER_STATUS_PREPARING = "PREPARING"
	ORDER_STATUS_DELIVERED = "DELIVERED"
	ORDER_STATUS_CANCELLED = "CANCELLED"
)

const (
	PAYMENT_METHOD_NETBANKING  = "NETBANKING"
	PAYMENT_METHOD_CREDIT_CARD = "CREDIT_CARD"
	PAYMENT_METHOD_DEBIT_CARD  = "DEBIT_CARD"
	PAYMENT_METHOD_UPI         = "UPI"
)

const (
	PAYMENT_STATUS_PENDING   = "PENDING"
	PAYMENT_STATUS_COMPLETED = "COMPLETED"
	PAYMENT_STATUS_FAILED    = "FAILED"
)
